### ISSUE TITLE
Example fails with "Re-exporting a type.."

### ISSUE THREAD

**Issue by jusjusjus** [asos-craigmorten/superoak#26]
# Issue

I followed the advertized example in creating a file "demo.test.ts" and ran `deno test --allow-net demo.test.ts` in a fresh directory.  Here's the output:
```
Check file:///.../deno/testing/demo.test.ts
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { AsyncReturnType } from "./AsyncReturnType.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.8.0/tools/typeSafety/index.ts:2:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackPromise } from "./UnpackPromise.ts";
         ~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.8.0/tools/typeSafety/index.ts:8:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackTypeGuard } from "./UnpackTypeGuard.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.8.0/tools/typeSafety/index.ts:9:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Ctx, DoneOrAborted } from "./Ctx.ts";
         ~~~
    at https://deno.land/x/evt@1.8.0/lib/types/interfaces/index.ts:1:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Ctx, DoneOrAborted } from "./Ctx.ts";
              ~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.8.0/lib/types/interfaces/index.ts:1:15

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { CtxLike, VoidCtxLike } from "./CtxLike.ts";
                  ~~~~~~~~~~~
    at https://deno.land/x/evt@1.8.0/lib/types/interfaces/index.ts:2:19

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Evt } from "./Evt.ts";
         ~~~
    at https://deno.land/x/evt@1.8.0/lib/types/interfaces/index.ts:3:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { NonPostableEvt } from "./NonPostableEvt.ts";
         ~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.8.0/lib/types/interfaces/index.ts:4:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Postable } from "./Postable.ts";
...
```

Setup:

- Deno Version: 1.16.1
- v8 Version: 9.7.106.2
- Typescript Version: 4.4.2
- SuperOak Version: 2.1.0

**Comment by cmorten** [comment]
Hey @jusjusjus :wave:

I've just released a https://deno.land/x/superoak@4.5.0 version, can you try that out and check if the issue is resolved?

**Comment by cmorten** [comment]
Ah just noticed you're using version `2.1.0`, definitely recommend updating to one of the latest versions! 😄

**Comment by asos-craigmorten** [comment]
Unable to reproduce with the latest version - please reopen if you are still facing the issue.
